apiVersion: v1
kind: Service
metadata:
  name: belgian-beers
  labels:
    app: belgian-beers
spec:
  ports:
  - name: belgian-beers
    port: 3000
  selector:
    app: belgian-beers
  type: LoadBalancer